-- Create the ReferenceTable
CREATE TABLE CorrectNameandSEX (
    Name NVARCHAR(50),
    Sex CHAR(1) -- 'M' for male, 'F' for female
);

-- Insert Names and Corresponding Sexes
INSERT INTO CorrectNameandSEX (Name, Sex)
VALUES
('Adel', 'M'),
('Ahmed', 'M'),
('Aicha', 'F'),
('Ali', 'M'),
('Amal', 'F'),
('Amel', 'F'),
('Amina', 'F'),
('Amine', 'M'),
('Amira', 'F'),
('Anis', 'M'),
('Anouar', 'M'),
('Asma', 'F'),
('Aya', 'F'),
('Aymen', 'M'),
('Ayoub', 'M'),
('Bassem', 'M'),
('Bilal', 'M'),
('Chaima', 'F'),
('Chaker', 'M'),
('Chiraz', 'F'),
('Chokri', 'M'),
('Cyrine', 'F'),
('Fares', 'M'),
('Fatma', 'F'),
('Feriel', 'F'),
('Ghazi', 'M'),
('Hajer', 'F'),
('Hamdi', 'M'),
('Hamza', 'M'),
('Hassen', 'M'),
('Hatem', 'M'),
('Hedi', 'M'),
('Hichem', 'M'),
('Houssem', 'M'),
('Imen', 'F'),
('Ines', 'F'),
('Jihene', 'F'),
('Karim', 'M'),
('Kenza', 'F'),
('Khadija', 'F'),
('Khaled', 'M'),
('Leila', 'F'),
('Maher', 'M'),
('Manel', 'F'),
('Marwa', 'F'),
('Marwen', 'M'),
('Med Amine', 'M'),
('Mehdi', 'M'),
('Meriem', 'F'),
('Mohamed', 'M'),
('Mohamed Ali', 'M'),
('Moncef', 'M'),
('Mouna', 'F'),
('Myriam', 'F'),
('Nada', 'F'),
('Nadia', 'F'),
('Nesrine', 'F'),
('Nour', 'F'),
('Noura', 'F'),
('Oumayma', 'F'),
('Oussama', 'M'),
('Rahma', 'F'),
('Rami', 'M'),
('Ramzi', 'M'),
('Rania', 'F'),
('Rawia', 'F'),
('Rym', 'F'),
('Sabrine', 'F'),
('Safa', 'F'),
('Salma', 'F'),
('Sami', 'M'),
('Samir', 'M'),
('Sana', 'F'),
('Sarra', 'F'),
('Selma', 'F'),
('Skander', 'M'),
('Slim', 'M'),
('Sofiane', 'M'),
('Sofien', 'M'),
('Walid', 'M'),
('Wassim', 'M'),
('Yasmine', 'F'),
('Yassine', 'M'),
('Yosra', 'F'),
('Youssef', 'M'),
('Zaineb', 'F'),
('Zohra', 'F');
